liteflow:
  rule-source-ext-data-map:
    url: jdbc:mysql://localhost:3306/wjhub #--数据库连接
    driverClassName: com.mysql.cj.jdbc.Driver #--驱动
    username: root #--用户名
    password: 32317128abc #--密码
    applicationName: flow
    chainTableName: liteflow_chain #--规则引擎表
    chainApplicationNameField: application_name #--应用名称
    chainNameField: chain_name  #--规则名称
    elDataField: el_data  #--具体执行的规则(el表达式)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wjhub?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 32317128abc

  application:
    name: flowgpt

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.flow.domain

# gpt:
gpt:
  chat-gpt:
    apiHost: https://dgr.life/
    apiKey:
      -   sk-xxxx

#
#liteflow:
#  rule-source-ext-data-map:
#    url: jdbc:mysql://localhost:3306/wjhub
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 32317128abc
#    applicationName: demo
#    #以下是chain表的配置，这个一定得有
#    chainTableName: chain
#    chainApplicationNameField: application_name
#    chainNameField: chain_name
#    elDataField: el_data
#    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
#    scriptTableName: script
#    scriptApplicationNameField: application_name
#    scriptIdField: script_id
#    scriptNameField: script_name
#    scriptDataField: script_data
#    scriptTypeField: script_type
#    #以下是轮询机制的配置
#    pollingEnabled: true
#    pollingStartSeconds: 0
#    pollingIntervalSeconds: 5